filebeat.inputs:
  - type: filestream
    id: apache-access
    enabled: true
    paths:
      - /var/log/apache/access.log
    fields:
      service: apache
    fields_under_root: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "apache-logs"
  pipeline: "apache_ingest_pipeline"

setup.template.enabled: false
setup.ilm.enabled: false

logging.level: info
